<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="192210" started-at="2018-08-23T10:47:55Z" finished-at="2018-08-23T10:51:07Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="192210" started-at="2018-08-23T10:47:55Z" finished-at="2018-08-23T10:51:07Z">
      <class name="validate.TestyouLogin">
        <test-method status="PASS" signature="TestYouLoginCase1()[pri:0, instance:validate.TestyouLogin@7dc7cbad]" name="TestYouLoginCase1" duration-ms="101399" started-at="2018-08-23T16:17:55Z" finished-at="2018-08-23T16:19:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestYouLoginCase1 -->
        <test-method status="FAIL" signature="TestYouLoginCase2()[pri:0, instance:validate.TestyouLogin@7dc7cbad]" name="TestYouLoginCase2" duration-ms="90542" started-at="2018-08-23T16:19:36Z" finished-at="2018-08-23T16:21:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [My Title] but found [Student Dashboard | Test Maker - TestYou]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [My Title] but found [Student Dashboard | Test Maker - TestYou]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at validate.TestyouLogin.TestYouLoginCase2(TestyouLogin.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestYouLoginCase2 -->
      </class> <!-- validate.TestyouLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
